### ISSUE TITLE
ValueError: Shapes (2, 1) and () are incompatible

### ISSUE THREAD

**Issue by heikog** [lmb-freiburg/hand3d#2]
I wanted to play around with your work but im getting the above error when executing run.py
annysuggestions ? Its TF 1.1
tia

**Comment by zimmerm** [comment]
The problems you are experiencing are due to changes that were made to the Tensorflow API. 
Starting with [TF 1.0](https://github.com/tensorflow/tensorflow/releases/tag/v1.0.0) they renamed and changed the interface of some functions. 

I was able to get it working on my machine with the following changes:
Change the order of arguments for all calls of tf.concat from "tf.concat(axis, [i1, i2])" to  "tf.concat([i1, i2], axis)".
Add the following lines to "utils.py" after the import statements:
```
tf.pack = tf.stack
tf.select = tf.where
tf.batch_matmul = tf.matmul
```

Or maybe its easier for you to use the TF version mentioned [here](https://github.com/lmb-freiburg/hand3d#recommended-system).

As soon as I find time I'll upgrade the code in repository to be compatible with the current release of Tensorflow.

**Comment by heikog** [comment]
Thanks for your quick reply. Ill give it a shot

**Comment by Revin-yu** [comment]
I have the same problem, can you help me solve it?
ValueError: Shapes (3, 3, 3, 64) and (64, 1, 3, 3) are incompatible
