### ISSUE TITLE
Can a pre-trained model be provided

### ISSUE THREAD

**Issue by momo1986** [lmb-freiburg/hand3d#26]
Hello,
Thanks for your sharing.
I am working on an environment with only four 1080 titian GPUs, I am not sure whether it can be trained if it has other tasks running.
I am not sure whether the lmb-freiburg can provide a pre-trained model?
Thanks

**Comment by josecyc** [comment]
Also, looking for some pre-trained weights. I tried running the forward pass with the weights provided but the results were pretty imprecise.

**Comment by f-jiang** [comment]
Has anyone tried doing the training using a cloud service like Google Cloud AI Platform?

**Comment by josecyc** [comment]
Hey, 
This are my results with a forward pass with run.py

As you can see in this first image results are pretty far away from what is presented in the paper, even though I'm using your pre-trained weights.
<img width="1322" alt="Screen Shot 2019-05-26 at 5 35 41 PM" src="https://user-images.githubusercontent.com/19275925/58389205-2cf0f680-7fdd-11e9-8c44-f92943328e88.png">

<img width="637" alt="Screen Shot 2019-05-26 at 5 34 08 PM" src="https://user-images.githubusercontent.com/19275925/58389210-35e1c800-7fdd-11e9-81d8-593c42a757da.png">

Own image test
<img width="636" alt="Screen Shot 2019-05-26 at 5 34 38 PM" src="https://user-images.githubusercontent.com/19275925/58389206-30847d80-7fdd-11e9-90c1-ac00fe1ceb25.png">

Could you guys provide some insight into why this is happening please?

**Comment by zimmerm** [comment]
@momo1986 There are pretrained weights available. Check the README for information on how to download them.
@josecyc The example from run.py example yields exactly the results from the paper. I suspect, that you either changed something in the code or its some weird issue caused by different versions or operating systems. I use Ubuntu and can't guaratee anything for OsX. However, it looks like your images don't have the right channel order RGB vs. BGR.
